# Generated by Django 3.2 on 2021-07-29 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_alter_inspection_log_substation_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_log',
            name='substations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_to_substation', to='inspection.substation', verbose_name='substation'),
        ),
    ]
