# Generated by Django 3.2.5 on 2021-09-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_inspection_log_substations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection_log',
            name='substations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_to_substation', to='inspection.substation', verbose_name='substation'),
        ),
    ]
