# Generated by Django 3.2.5 on 2021-07-16 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection_log',
            name='job_type',
            field=models.CharField(default='repairs', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspection_log',
            name='date_record',
            field=models.DateField(default=datetime.date(2021, 7, 16), verbose_name='Date of Record'),
        ),
        migrations.AlterField(
            model_name='inspection_log',
            name='substation_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
