# Generated by Django 3.2 on 2021-07-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_auto_20210723_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection_log',
            name='substation_img',
            field=models.ImageField(blank=True, null=True, upload_to='%Y%m%d/'),
        ),
    ]
