# Generated by Django 4.0.4 on 2022-05-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_alter_inspection_log_substations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection_log',
            name='record',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Record'),
        ),
    ]
